name: get RQ data and write to google sheet

on:
  workflow_dispatch:
  schedule:
#    schedule默认时区间是UTC+0， 对应北京时间22:30
    - cron: "30 16 * * *"
  push:
    branches:
      - main

env:
  # please change to your own config.
  RQ_COOKIE: ${{ secrets.RQ_COOKIE }}
  RQ_CSRF_TOKEN: ${{ secrets.RQ_CSRF_TOKEN }}
  RQ_USERID: ${{ secrets.RQ_USERID }}
  GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
  GOOGLE_API_CLIENT_EMAIL: ${{ secrets.GOOGLE_API_CLIENT_EMAIL }}
  GOOGLE_API_PRIVATE_KEY: ${{ secrets.GOOGLE_API_PRIVATE_KEY }}
  BARK_KEY: ${{ secrets.BARK_KEY }}
  GITHUB_NAME: gooin
  GITHUB_EMAIL: gooin@@outlook.com

jobs:
  build:
    runs-on: ubuntu-latest
    name: get RQ data and write to google sheet
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn
      - run: yarn start
