name: Run Data Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - scripts/nike_sync.py
      - scripts/nike_to_strava_sync.py
      - scripts/runtastic_sync.py
      - scripts/strava_sync.py
      - scripts/gen_svg.py
      - scripts/garmin_sync.py
      - scripts/keep_sync.py
      - scripts/gpx_sync.py
      - requirements.txt

env:
  # please change to your own config.
  RUN_TYPE: garmin_cn # support runtastic/strava/nike/garmin/garmin_cn/keep/only_gpx/nike_to_strava, Please change the 'pass' it to your own
  ATHLETE: Zhitao
  TITLE: Zhitao Running
  TITLE_GRID: Over 10km Runs
  GITHUB_NAME: gooin
  GITHUB_EMAIL: gooin@@outlook.com

jobs:
  build:
    runs-on: ubuntu-latest
    name:Use Node.js
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn
      - run: yarn start
