name: rq-sigin-sync

on:
  workflow_dispatch:
  schedule:
    - cron: '30 9,10,16 * * *'
env:
  GITHUB_NAME: ${{ secrets.GITHUB_NAME }}
  GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.2"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run RQ Sigin Sync
      run: |
        python scripts/rq_sgin.py --email=${{ secrets.RQ_EMAIL }} --password=${{ secrets.RQ_PASSWORD }} --AESKEY=${{ secrets.AESKEY }}
    - name: Push new runs
      run: |
        git config --local user.email "${{ env.GITHUB_EMAIL }}"
        git config --local user.name "${{ env.GITHUB_NAME }}"
        git add .
        git commit -m 'update token' || echo "nothing to commit"
        git push || echo "nothing to push"